[project]
name = "omop-constructs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Georgie Kennedy", email = "georgina.kennedy@unsw.edu.au" }
]
requires-python = ">=3.12"
dependencies = [
    "omop-alchemy",
    "omop-semantics",
    "sqlalchemy>=2.0.45",
]

[project.scripts]
omop-constructs = "omop_constructs.cli:main"

[build-system]
requires = ["uv_build>=0.9.2,<0.10.0"]
build-backend = "uv_build"

[tool.uv.sources]
omop-alchemy = { git = "https://github.com/AustralianCancerDataNetwork/OMOP_Alchemy/" }
omop-semantics = { git = "https://github.com/AustralianCancerDataNetwork/OMOP_Semantics/" }
